services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - task_net
  redis:
    image: redis:8
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - task_net

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

    networks:
      - task_net

networks:
  task_net: null
 
volumes:
  pgdata: null
