FROM node:22

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app files
COPY . .

# Give execution permission to entrypoint script
RUN chmod +x docker-entrypoint.sh

# Expose port
EXPOSE 3000

ENV NODE_ENV=development

# Set entrypoint
ENTRYPOINT ["./docker-entrypoint.sh"]

# Default command
CMD ["npm", "run", "dev"]
