name: Run Migrations

on:
  push:
    branches: ["main"]

jobs:
  migrate-dev-db:
    name: Apply migrations to Development DB
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      - name: Verify migration
        run: npx prisma migrate status

  migrate-production:
    name: Apply Prisma Migrations to Production
    runs-on: ubuntu-latest
    needs:
      - migrate-dev-db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Apply Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Verify DB Connection
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: |
          npx prisma db pull
          echo "Database is healthy, migrations applied successfully!"
